[project]
name = "jura-bsbe"
version = "0.1.0"
description = "Tool to compare bsbe pargraphs from German ferderal states"
authors = [
    {name = "stefanieradnik",email = "stefanie.radnik@web.de"}
]
readme = "README.md"
requires-python = "==3.12"
dependencies = [
"streamlit==1.57.0",
"pyyaml==6.0.3",
"beautifulsoup4==4.14.3",
"thefuzz==0.22.1"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
target-version = ["py312"]
line-length = 100
